#!yaml
version: '3'
services:
  postgrest:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: "postgres://postgres:postgres@db:5432/dvdrental"
      PGRST_OPENAPI_SERVER_PROXY_URI: "http://127.0.0.1:3000"
      PGRST_DB_SCHEMAS: "public"
      PGRST_DB_ANON_ROLE: "postgres"
      PGRST_DB_POOL: "10"
      PGRST_SERVER_HOST: "*4"
      PGRST_SERVER_PORT: "3000"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    image: dvdrentalspgs
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dvdrental
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  postgui:
    build:
      context: .
      dockerfile: Dockerfile-postgui
    image: postgui
    depends_on:
      - postgrest
    ports:
      - "8771:8771"
