FROM postgres:latest
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres
ENV POSTGRES_DB dvdrental
COPY dvdrental.tar .
COPY CREATE-FUNCTION.sql .
COPY CREATE-ROLE.sql .
COPY Authentication.sql .
ADD pgjwt /pgjwt
RUN apt-get update && apt-get install -y make
WORKDIR "/pgjwt"
RUN make && make install
COPY init.sh /docker-entrypoint-initdb.d/initialize.sh