apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:

- name: nginx-postgui
  namespace: postgui
  files:
    - files/nginx-postgui.conf

- name: nginx-postgrest
  namespace: postgui
  files:
    - files/nginx-postgrest.conf

- name: postgui-config-json
  namespace: postgui
  files:
    - files/config.json

resources:
- ../../base
- domains.yaml

patchesStrategicMerge:
- deployment.yaml