apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgui

configMapGenerator:
- name: postgui-nginx-proxy
  files:
    - files/nginx-proxy.conf
- name: postgui-config-json
  files:
    - files/config.json

resources:
- ../../base

patchesStrategicMerge:
- deployment.yaml