apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgui
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: postgui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: postgui
    spec:
      volumes:
        - name: nginx-postgui
          configMap:
            name: nginx-postgui
        - name: nginx-postgrest
          configMap:
            name: nginx-postgrest
        - name: postgui-config-json
          configMap:
            name: postgui-config-json
      containers:
      - name: postgui-nginx
        image: nginx:1.20
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 256Mi
        volumeMounts:
          - name: nginx-postgui
            mountPath: /etc/nginx/conf.d/nginx-postgui.conf
            subPath: nginx-postgui.conf
          - name: nginx-postgrest
            mountPath: /etc/nginx/conf.d/nginx-postgrest.conf
            subPath: nginx-postgrest.conf
      - name: postgui-app
        image: agileforce/postgui:latest
        ports:
          - containerPort: 8771
        # resources:
        #   requests:
        #     memory: 256Mi
        #     cpu: 100m
        #   limits:
        #     memory: 512Mi
        volumeMounts:
          - name: postgui-config-json
            mountPath: /PostGUI/src/data/config.json
            subPath: config.json
      - name: postgres
        image: agileforce/dvdrental:latest
        ports:
          - containerPort: 5432
            name: postgres-svc
      - name: postgrest
        image: postgrest/postgrest
        ports:
          - containerPort: 3000
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 512Mi
