apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgui
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: postgui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: postgui
    spec:
      volumes:
        - name: postgui-nginx-proxy
          configMap:
            name: postgui-nginx-proxy
        - name: postgui-config-json
          configMap:
            name: postgui-config-json
      containers:
      - name: postgui-app
        image: agileforce/postgui:latest
        ports:
          - containerPort: 8771
        volumeMounts:
          - name: postgui-config-json
            mountPath: /PostGUI/src/data/config.json
            subPath: config.json
      - name: postgres
        image: agileforce/dvdrental:latest
        ports:
          - containerPort: 5432
            name: postgres-svc
      - name: postgrest
        image: postgrest/postgrest
        ports:
          - containerPort: 3000
      - name: postgui-nginx
        image: nginx:1.20
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 192Mi
        ports:
        - containerPort: 80
        volumeMounts:
          - name: postgui-nginx-proxy
            mountPath: /etc/nginx/conf.d/nginx-proxy.conf
            subPath: nginx-proxy.conf