apiVersion: v1
kind: Service
metadata:
  name: postgui-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: postgui
---
apiVersion: v1
kind: Service
metadata:
  name: postgrest
spec:
  ports:
  - name: tcp-postgrest
    port: 3000
    targetPort: 3000
  selector:
    app: postgui
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
  - name: tcp-postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgui
---
apiVersion: v1
kind: Service
metadata:
  name: postgui
spec:
  ports:
  - name: tcp-postgui
    port: 8771
    targetPort: 8771
  selector:
    app: postgui