apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgui-postgres
spec:        
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: postgui-postgres
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: postgui-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
